### ISSUE TITLE
解决Clone GitHub慢的问题 - Ethan's Tech Blog | 阎覃的技术Blog

### ISSUE THREAD

**Issue by Ethan-yt** [Ethan0w0/ethan0w0.github.io#12]
https://ethan-yt.github.io/2017/07/26/%E8%A7%A3%E5%86%B3Clone%20GitHub%E6%85%A2%E7%9A%84%E9%97%AE%E9%A2%98/

**Comment by EisenloCarter** [comment]
WTF
